C = gcc
CXX = clang++

SOURCE_C = 
OBJECTS_C =

SOURCE_CXX = 2.1.cpp

TARGET = 2.1
LDFLAGS_COMMON = -std=c++2a

all:
	$(CXX) $(SOURCE_CXX) $(LDFLAGS_COMMON) -o $(TARGET)

clean:
	rm -rf *.o $(TARGET)
